EventBookingSystemMVC/Controllers/ApprovalController.cs
using EventTicketBookingSystemData.Model;
using EventTicketBookingSystemMVC.Service.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EventTicketBookingSystemMVC.Controllers
{
   //[Area("Admin")]

    [Authorize(Roles ="Admin")]
    public class ApprovalController : Controller
    {

        private readonly IApprovalService _approvalService;

        public ApprovalController(IApprovalService approvalService)
        {
            _approvalService = approvalService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _approvalService.GetUsersAsync();
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> ApproveEvent(int id)
        {
            try
            {
                await _approvalService.ApproveEvent(id);
                TempData["Success"] = "Approved";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("Index");
            }
        }

        [HttpGet]
        public async Task<IActionResult> RejectEvent(int id)
        {
            try
            {
                await _approvalService.RejectEvent(id);
                TempData["Success"] = "Rejected Successfully";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("Index");
            }
        } 
    }
}

EventBookingSystemMVC/Controllers/CustomerController.cs
using EventTicketBookingSystemData.Model; // Make sure to import the Customer model
using EventTicketBookingSystemMVC.Models; // Make sure to import the CustomerViewModel
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Threading.Tasks;

namespace EventTicketBookingSystemMVC.Controllers
{
    public class CustomerController : Controller
    {
        private readonly HttpClient _httpClient;

        public CustomerController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient(); // Create a new HttpClient instance through DI
            _httpClient.BaseAddress = new Uri("https://localhost:7264"); // Set the base address of your API
            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        public async Task<IActionResult> Index()
        {
            List<CustomerViewModel> customersViewModel = new List<CustomerViewModel>();

            // Call the API to get customer data
            HttpResponseMessage response = await _httpClient.GetAsync("/api/Customer");
            if (response.IsSuccessStatusCode)
            {
                var jsonResult = await response.Content.ReadAsStringAsync();
                List<Customer> customers = JsonConvert.DeserializeObject<List<Customer>>(jsonResult);
                customersViewModel = customers.Select(c => MapToViewModel(c)).ToList();
            }

            return View(customersViewModel);
        }

        private CustomerViewModel MapToViewModel(Customer customer)
        {
            // Implement your mapping logic here to map Customer to CustomerViewModel
            return new CustomerViewModel
            {
                CustomerName = customer.CustomerName,
                CustomerEmail = customer.CustomerEmail,
                Password = customer.Password,
                // Map other properties as needed
            };
        }
    }
}

EventBookingSystemMVC/Controllers/EventController.cs
using EventTicketBookingSystemMVC.Models;
using EventTicketBookingSystemMVC.Service.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace EventTicketBookingSystemMVC.Controllers
{
  // [Authorize]
    public class EventController : Controller
    {
        private readonly IEventService _eventService;

        public EventController(IEventService eventService)
        {
            _eventService=eventService;
        }
        public async Task<IActionResult> Index()
        {
            List<EventViewModel> list = new();

            var response = await _eventService.GetAllAsync<APIResponse>();
            
            if (response != null)
            {
                list = JsonConvert.DeserializeObject<List<EventViewModel>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        public IActionResult AddEvent()
        {

            return View();
        }
        public async Task<IActionResult> Create(EventViewModel eventViewModel)
        {
          await  _eventService.CreateAsync<APIResponse>(eventViewModel);
            TempData["success"] = "Event created successfully";

            return RedirectToAction("Index");
        }
        public IActionResult editpage(int id)
        {
          
            var response= _eventService.Getbyid<APIResponse>(id);
            var data = Convert.ToString(response.Result.Result);
            if (response != null) {
                EventViewModel eventViewModel=JsonConvert.DeserializeObject<EventViewModel>(data);
                return View(eventViewModel);
            }

       
            return View();
        }
        public async Task<ActionResult> Edit(EventViewModel eventViewModel)
        {
            await _eventService.UpdateAsync<APIResponse>(eventViewModel);
            TempData["success"] = "Event updated successfully";
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> Delete(int id)
        {
            await _eventService.DeleteAsync<APIResponse>(id);
            TempData["success"] = "Event deleted successfully";
            return RedirectToAction("Index");
        }
        #region API CALLS

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {

            List<EventViewModel> list = new();

            var response = await _eventService.GetAllAsync<APIResponse>();

            if (response != null)
            {
                list = JsonConvert.DeserializeObject<List<EventViewModel>>(Convert.ToString(response.Result));
            }

            return Json(new { data = list });


        }

        #endregion
    }
}

EventBookingSystemMVC/Controllers/TicketBookingController.cs
using EventTicketBookingSystemMVC.Models;
using EventTicketBookingSystemMVC.Service.IService;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace EventTicketBookingSystemMVC.Controllers
{
    public class TicketBookingController : Controller
    {
        private readonly ITicketBookingService _ticketBookingService;
        private readonly IEventService _eventService;
        private readonly ICustomerService _customerService;
        private readonly UserManager<IdentityUser> _UserManagerr;

        public TicketBookingController(ITicketBookingService ticketBookingService, IEventService eventService, ICustomerService customerService, UserManager<IdentityUser> UserManager)
        {
            _ticketBookingService=ticketBookingService;
            _eventService=eventService;
            _customerService=customerService;
            _UserManagerr=UserManager;
        }
       
        public async Task<IActionResult> Index()
        {
            List<TicketBookingViewModel> list = new();

            var response = await _ticketBookingService.GetAllAsync<APIResponse>();

            if (response != null)
            {
                list = JsonConvert.DeserializeObject<List<TicketBookingViewModel>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        public IActionResult CreateBooking(int eventid)
        {
            TempData["Eventid"]=eventid;

            return View();
        }
        public async Task<IActionResult> Create(TicketBookingViewModel ticketBookingViewModel)
        { ticketBookingViewModel.Id=0;
            ticketBookingViewModel.EventId=Convert.ToInt32( TempData["Eventid"]);
            ticketBookingViewModel.ApprovedStatus="Pending";
            ticketBookingViewModel.CustomerEmail = User.Identity.Name;
            await _ticketBookingService.CreateAsync<APIResponse>(ticketBookingViewModel);
            TempData["success"] = "Booking created successfully";
            return RedirectToAction("Index");
        }


        public async Task<ActionResult> Updatebyid(int id) {
            await _ticketBookingService.Updatebyid<APIResponse>(id);
            TempData["success"] = "Approved successfully";
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> UpdatebyidReject(int id)
        {
            await _ticketBookingService.UpdatebyidReject<APIResponse>(id);
            TempData["success"] = "Rejected successfully";
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete(int id)
        {
            await _ticketBookingService.DeleteAsync<APIResponse>(id);
            TempData["success"] = "Booking deleted successfully";
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            ViewData["Bookid"]=id;
           
            TicketBookingViewModel ticketBookingViewModel =new TicketBookingViewModel();
            CustomerViewModel customerViewModelS = new();
            EventViewModel eventViewModel=new EventViewModel();

            var detailsofticket = _ticketBookingService.Getbyid<APIResponse>(id);
            if (detailsofticket != null) { 

               ticketBookingViewModel = JsonConvert.DeserializeObject<TicketBookingViewModel>(Convert.ToString(detailsofticket.Result.Result)); 
            }
            var detailsofevent = _eventService.Getbyid<APIResponse>(ticketBookingViewModel.EventId);
            if (detailsofevent != null)
            {
               
              eventViewModel = JsonConvert.DeserializeObject<EventViewModel>(Convert.ToString(detailsofevent.Result.Result));
            }
                var cutsmoerdeatils = _customerService.Getbyid<APIResponse>(ticketBookingViewModel.CustomerEmail);
            
            if (cutsmoerdeatils != null)
            {
               customerViewModelS = JsonConvert.DeserializeObject<CustomerViewModel>(Convert.ToString(cutsmoerdeatils.Result.Result));
            }
                TicketbookingDetails ticketbookingDetails = new TicketbookingDetails()
                    
            {
                customerViewModel=customerViewModelS,
                EventViewModel=eventViewModel
            };

            ticketbookingDetails.customerViewModel.Password="";

            return View(ticketbookingDetails);

        }
        //public IActionResult aprovereject()
        //{

        //}

    }
}

EventBookingSystemMVC/Views/Shared/_Layout.cshtml
<head>
    <!-- Other meta tags and links go here -->
    <link rel="stylesheet" href="~/css/site.css">
</head>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventBookingSystemMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EventBookingSystemMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventBookingSystemMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Index">Event</a>
                        </li>
                        @if(User.IsInRole(SD.Role_Admin))
                      
                        {  
                          <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                          </li>

                        }
                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TicketBooking" asp-action="Index">TicketBooking</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Approval" asp-action="Index">EventsApproved</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer bg-dark text-white">
        <div class="text-center">
            Abhishek Kumar Chaudhary &copy; 2023. All rights reserved.
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EventBookingSystemMVC/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]');
    </script>
}